from typing import Protocol, List, Optional
import uuid
from app.domain.entities.delivery import Delivery as DeliveryEntity

class DeliveryRepositoryProtocol(Protocol):
    """Repositório para operações de persistência de entregas."""
    async def create(self, entity: DeliveryEntity) -> DeliveryEntity: ...

    async def list_all(self, limit: int = 50, offset: int = 0) -> List[DeliveryEntity]: ...

    async def get_by_id(self, delivery_id: uuid.UUID) -> Optional[DeliveryEntity]: ...

    async def update(self, entity: DeliveryEntity) -> DeliveryEntity: ...

    async def count_by_status(self) -> dict[str, int]: ...

    async def count_delayed(self) -> int: ...
