from typing import Protocol, List
from app.domain.entities.place import Factory as FactoryEntity, Store as StoreEntity

class PlaceRepositoryProtocol(Protocol):
    async def create_factory(self, factory_entity: FactoryEntity) -> FactoryEntity: ...

    async def list_factories(self, limit: int = 50, offset: int = 0) -> List[FactoryEntity]: ...

    async def create_store(self, store_entity: StoreEntity) -> StoreEntity: ...

    async def list_stores(self, limit: int = 50, offset: int = 0) -> List[StoreEntity]: ...
