"""Init

Revision ID: 17589825805b
Revises: 
Create Date: 2026-03-31 20:14:10.627968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17589825805b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('store',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('eta_original', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_current', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_driver_id'), 'delivery', ['driver_id'], unique=False)
    op.create_index(op.f('ix_delivery_store_id'), 'delivery', ['store_id'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_delivery_id'), 'alert', ['delivery_id'], unique=False)
    op.create_table('chaoseventlog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('impact_factor', sa.Float(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('lat_start', sa.Float(), nullable=True),
    sa.Column('lng_start', sa.Float(), nullable=True),
    sa.Column('lat_end', sa.Float(), nullable=True),
    sa.Column('lng_end', sa.Float(), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timestamp_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chaoseventlog_delivery_id'), 'chaoseventlog', ['delivery_id'], unique=False)
    op.create_table('etahistory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('eta_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etahistory_delivery_id'), 'etahistory', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etahistory_delivery_id'), table_name='etahistory')
    op.drop_table('etahistory')
    op.drop_index(op.f('ix_chaoseventlog_delivery_id'), table_name='chaoseventlog')
    op.drop_table('chaoseventlog')
    op.drop_index(op.f('ix_alert_delivery_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_delivery_store_id'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_driver_id'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_table('store')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('factory')
    # ### end Alembic commands ###
